version: '3'

services:
  ieportals:
    build:
      context: .
      dockerfile: Dockerfile.local  # Pointing to the development Dockerfile
    image: ieportals-local-image
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
